# --- Labels ---
class Unregistered: ...
class Registrable: ...
# --- Persistence ---
class NonPersistent: ...
# --- Regions
class LinkDue: ...
class NodeRegionsDue: ...
class LinkRegionsDue: ...
# --- Velocity ---
class VelocityDue: ...
# --- Movement ---
class AdvanceRoute: ...
class EndRoute: ...