# --- Persistence ---
class NewEntity: ...
class NonPersistent: ...
# --- Regions
class LinkDue: ...
class NodeRegionsDue: ...
class LinkRegionsDue: ...
# --- Velocity ---
class VelocityDue: ...
# --- Movement ---
class AdvanceRoute: ...
class EndRoute: ...